CURRENT_DIR=$(readlink -f .)

CONFIG_DIR=$CURRENT_DIR/config
DATA_DIR=$CURRENT_DIR/nodes-data
BUILD_DIR=$CURRENT_DIR/build

PRYSM_DATA_DIR=$DATA_DIR/data-prysm
GETH_DATA_DIR=$DATA_DIR/data-geth
VALIDATOR_DATA_DIR=$DATA_DIR/validator

PRYSM_DIR=./prysm
GETH_DIR=./go-ethereum

ACCOUNT_ADDRESS=0x08385bD3728d296a3C3566A59b07a970745C87fE
FEE_RECIPIENT=$ACCOUNT_ADDRESS